version: '3.3'

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  sample-rest-service:
    build: .
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mysecretpassword'
      POSTGRES_DB: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_HOSTNAME: postgres
    ports:
      - "8080:8080"
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", "-Djava.security.egd=file:/dev/./urandom", "-Xmx200m", "-jar", "/app/app.jar"]
    depends_on:
      - postgres

volumes:
  db-data:
